\c dw

-- ============================================================================
-- Data mart dimensional (Kimball), schema `public` do banco `dw`, derivado do
-- corporativo (../dw/dw_postgres.sql) - nunca lido direto do OLTP `datatran`
-- (ver airflow/dags/common_etl.py).
--
-- Grão do fato: 1 ocorrência (mesmo grão do CSV original e de
-- corporativo.ocorrencias) - não há granularidade por vítima ou por veículo
-- neste mart, porque a fonte não tem.
--
-- Decisão de modelagem registrada: as 9 classificações do acidente
-- (causa_acidente, tipo_acidente, classificacao_acidente, fase_dia,
-- sentido_via, condicao_metereologica, tipo_pista, tracado_via, uso_solo) -
-- que no OLTP e no corporativo são um catálogo atributo-valor genérico
-- (`acidente_atributo`/`ocorrencia_classificacao`) - viram aqui uma única
-- DIMENSÃO JUNK (`dim_classificacao_acidente`): uma linha por COMBINAÇÃO das
-- 9 flags realmente observada nos dados (não o produto cartesiano teórico),
-- em vez de 9 dimensões separadas ou 9 FKs soltas no fato. É o padrão Kimball
-- para agrupar várias flags/atributos de baixo-médio cardinalidade
-- correlacionados que, sozinhos, não justificam uma dimensão própria nem
-- valem a pena ficar "soltos" como degenerate dimension (são 9 campos, não
-- 1). Cada campo usa 'Não informado' no lugar de NULL exatamente para a
-- UNIQUE da dimensão funcionar - Postgres trata NULL como distinto de NULL,
-- então duas ocorrências sem `condicao_metereologica` (por exemplo) gerariam
-- duas linhas "iguais" na dimensão sem esse cuidado.
--
-- `dim_local`: equivalente conformado de `corporativo.locais_acidente`, mas
-- já desnormalizado (nome do município, sigla/nome da UF, número da rodovia,
-- km) numa única linha - sem exigir 3 JOINs (municipio/uf/localizacao/rodovia)
-- pra uma consulta de BI simples.
-- ============================================================================

-- ----------------------------
-- DIMENSÕES
-- ----------------------------

CREATE TABLE dim_tempo (
    id_dim_tempo INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data DATE NOT NULL,
    dia INT NOT NULL,
    mes INT NOT NULL,
    nome_mes VARCHAR(20) NOT NULL,
    trimestre INT NOT NULL,
    ano INT NOT NULL,
    dia_semana VARCHAR(20) NOT NULL,
    flag_fim_semana BOOLEAN NOT NULL,
    UNIQUE (data)
);

CREATE TABLE dim_local (
    id_dim_local INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sistema_origem VARCHAR(20) NOT NULL,
    id_local_original VARCHAR(50) NOT NULL, -- corporativo.locais_acidente.id_local, como texto
    nome_municipio VARCHAR(60) NOT NULL,
    sigla_uf CHAR(2) NOT NULL,
    nome_uf VARCHAR(30) NOT NULL,
    numero_rodovia SMALLINT NOT NULL,
    km NUMERIC(6,1) NOT NULL,
    data_carga TIMESTAMP NOT NULL DEFAULT now(),
    UNIQUE (sistema_origem, id_local_original)
);

CREATE TABLE dim_classificacao_acidente (
    id_dim_classificacao INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    causa_acidente VARCHAR(60) NOT NULL DEFAULT 'Não informado',
    tipo_acidente VARCHAR(60) NOT NULL DEFAULT 'Não informado',
    classificacao_acidente VARCHAR(60) NOT NULL DEFAULT 'Não informado',
    fase_dia VARCHAR(60) NOT NULL DEFAULT 'Não informado',
    sentido_via VARCHAR(60) NOT NULL DEFAULT 'Não informado',
    condicao_metereologica VARCHAR(60) NOT NULL DEFAULT 'Não informado',
    tipo_pista VARCHAR(60) NOT NULL DEFAULT 'Não informado',
    tracado_via VARCHAR(60) NOT NULL DEFAULT 'Não informado',
    uso_solo VARCHAR(60) NOT NULL DEFAULT 'Não informado',
    data_carga TIMESTAMP NOT NULL DEFAULT now(),
    UNIQUE (causa_acidente, tipo_acidente, classificacao_acidente, fase_dia, sentido_via,
            condicao_metereologica, tipo_pista, tracado_via, uso_solo)
);

-- ----------------------------
-- FATO
-- ----------------------------
-- Medidas pré-agregadas por categoria de vítima (pivotadas a partir de
-- corporativo.ocorrencia_vitima) - ao contrário do OLTP/corporativo, aqui a
-- redundância de guardar `pessoas`/`feridos` já calculados é desejada: é
-- exatamente o que torna o fato somável direto num BI sem reconstruir o
-- pivot toda consulta.

CREATE TABLE fato_acidentes (
    id_fato_acidente BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sistema_origem VARCHAR(20) NOT NULL,
    id_ocorrencia_original VARCHAR(50) NOT NULL,
    id_dim_tempo INT NOT NULL REFERENCES dim_tempo (id_dim_tempo),
    id_dim_local INT REFERENCES dim_local (id_dim_local), -- NULL: ocorrências sem uf/br/km na fonte
    id_dim_classificacao INT NOT NULL REFERENCES dim_classificacao_acidente (id_dim_classificacao),
    veiculos SMALLINT NOT NULL,
    mortos SMALLINT NOT NULL DEFAULT 0,
    feridos_leves SMALLINT NOT NULL DEFAULT 0,
    feridos_graves SMALLINT NOT NULL DEFAULT 0,
    ilesos SMALLINT NOT NULL DEFAULT 0,
    ignorados SMALLINT NOT NULL DEFAULT 0,
    feridos SMALLINT NOT NULL DEFAULT 0,  -- feridos_leves + feridos_graves, pré-calculado
    pessoas SMALLINT NOT NULL DEFAULT 0,  -- soma das 5 categorias, pré-calculado
    data_carga TIMESTAMP NOT NULL DEFAULT now(),
    UNIQUE (sistema_origem, id_ocorrencia_original)
);

CREATE INDEX idx_fato_acidentes_tempo ON fato_acidentes (id_dim_tempo);
CREATE INDEX idx_fato_acidentes_local ON fato_acidentes (id_dim_local);
CREATE INDEX idx_fato_acidentes_classificacao ON fato_acidentes (id_dim_classificacao);

-- ----------------------------
-- POPULAÇÃO DA DIM_TEMPO
-- ----------------------------

INSERT INTO dim_tempo (data, dia, mes, nome_mes, trimestre, ano, dia_semana, flag_fim_semana)
SELECT
    d::date,
    EXTRACT(DAY FROM d)::int,
    EXTRACT(MONTH FROM d)::int,
    TO_CHAR(d, 'TMMonth'),
    EXTRACT(QUARTER FROM d)::int,
    EXTRACT(YEAR FROM d)::int,
    TO_CHAR(d, 'TMDay'),
    EXTRACT(ISODOW FROM d) IN (6, 7)
FROM generate_series('2000-01-01'::date, '2035-12-31'::date, interval '1 day') AS d;
