CREATE DATABASE dw;

\c dw

CREATE SCHEMA corporativo;

-- ============================================================================
-- Data Warehouse corporativo (camada "corporativo"), modelado à Inmon:
-- orientado por assunto, integrado, não-volátil e variante no tempo. Fonte:
-- banco `datatran` (OLTP, ver ../db/01_schema.sql) — acidentes de trânsito em
-- rodovias federais registrados pela PRF.
--
-- As 4 propriedades de Inmon aplicadas aqui:
--
--   ORIENTADO POR ASSUNTO: as tabelas não replicam a aplicação de origem
--   (que já é assunto único, "acidentes"), mas são organizadas pelos temas de
--   negócio que um analista corporativo consulta - Tempo, Geografia e Via,
--   Classificação do Acidente, Vítimas, Ocorrências -
--   independente de qualquer detalhe de implementação do OLTP (ex.: o OLTP
--   guarda "onde" via `local_acidente`, aqui isso é o assunto "Geografia e
--   Via" por completo, `municipios`+`rodovias`+`localizacoes`+`locais_acidente`).
--
--   INTEGRADO: toda tabela de fato (`ocorrencias`) carrega `sistema_origem`
--   (fixo em 'PRF-DATATRAN' hoje) + `id_ocorrencia_origem` (chave natural do
--   CSV de origem) ao lado da chave substituta corporativa. Isso é o que dá
--   ao DW a propriedade de "integrado" do Inmon mesmo quando, como aqui,
--   existe hoje uma única fonte real: o objetivo é poder empilhar
--   `datatran2008.csv`, `datatran2009.csv` etc. no mesmo
--   `corporativo.ocorrencias` ano após ano, sem colisão de PK (o `id` do CSV
--   é único só dentro de um ano) e sem reprocessar o histórico já carregado
--   - exatamente o cenário de "integrar múltiplas cargas da mesma família de
--   sistemas" que a propriedade motiva, ainda que aqui não haja um segundo
--   sistema *diferente* como no projeto de referência (Mercearia+Northwind).
--
--   NÃO-VOLÁTIL: `ocorrencias`/`ocorrencia_vitima`/`ocorrencia_classificacao`
--   são append-only - uma vez carregada, uma ocorrência nunca sofre UPDATE,
--   só INSERT de ocorrências novas (ver airflow/dags/carga_incremental_dw.py).
--
--   VARIANTE NO TEMPO: cada ocorrência é permanentemente amarrada à
--   `id_tempo` em que aconteceu; a série histórica cresce, nunca é
--   sobrescrita.
--
-- Diferença deliberada em relação ao projeto de referência (DW_pos_atividades):
-- lá, `clientes`/`funcionarios`/`produtos` precisam de histórico versionado
-- (upsert_historizado, SCD2) porque atributos descritivos (renda, cargo,
-- preço) mudam ao longo do tempo para a MESMA chave natural. Aqui, nenhuma
-- entidade de apoio (`ufs`, `municipios`, `rodovias`, `localizacoes`,
-- `tipos_classificacao`, `classificacoes_validas`, `categorias_vitima`) tem
-- atributo descritivo que mude no dataset de origem - nome de município e
-- sigla de UF são efetivamente estáticos. Por isso este schema não usa
-- upsert_historizado em lugar nenhum: todas as tabelas de apoio usam upsert
-- simples (existe ou não pela chave natural), e a única coisa genuinamente
-- variante no tempo é a CHEGADA de ocorrências novas, não a mudança de
-- atributos de uma dimensão de apoio.
-- ============================================================================

-- ----------------------------
-- ASSUNTO: TEMPO
-- ----------------------------
-- Calendário corporativo, gerado uma vez (não vem do sistema transacional).
-- Cobre 2000-2035 para admitir cargas de anos de datatran anteriores e
-- futuros ao 2007 hoje disponível em dataset/datatran2007.csv.

CREATE TABLE corporativo.tempos (
    id_tempo INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data DATE NOT NULL,
    dia INT NOT NULL,
    mes INT NOT NULL,
    nome_mes VARCHAR(20) NOT NULL,
    trimestre INT NOT NULL,
    ano INT NOT NULL,
    dia_semana VARCHAR(20) NOT NULL,
    flag_fim_semana BOOLEAN NOT NULL,
    UNIQUE (data)
);

INSERT INTO corporativo.tempos (data, dia, mes, nome_mes, trimestre, ano, dia_semana, flag_fim_semana)
SELECT
    d::date,
    EXTRACT(DAY FROM d)::int,
    EXTRACT(MONTH FROM d)::int,
    TO_CHAR(d, 'TMMonth'),
    EXTRACT(QUARTER FROM d)::int,
    EXTRACT(YEAR FROM d)::int,
    TO_CHAR(d, 'TMDay'),
    EXTRACT(ISODOW FROM d) IN (6, 7)
FROM generate_series('2000-01-01'::date, '2035-12-31'::date, interval '1 day') AS d;

-- ----------------------------
-- ASSUNTO: GEOGRAFIA E VIA
-- ----------------------------
-- Mesma decomposição do OLTP (uf / municipio / rodovia / localizacao /
-- local_acidente), agora com chave substituta própria do corporativo e
-- `data_carga` de auditoria - populadas por upsert simples a partir do OLTP
-- (ver common_etl.get_or_create_uf / get_or_create_municipio / etc.).

CREATE TABLE corporativo.ufs (
    id_uf INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sigla CHAR(2) NOT NULL,
    nome VARCHAR(30) NOT NULL,
    data_carga TIMESTAMP NOT NULL DEFAULT now(),
    UNIQUE (sigla)
);

CREATE TABLE corporativo.municipios (
    id_municipio INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(60) NOT NULL,
    id_uf INT NOT NULL REFERENCES corporativo.ufs (id_uf),
    data_carga TIMESTAMP NOT NULL DEFAULT now(),
    UNIQUE (nome, id_uf)
);

CREATE TABLE corporativo.rodovias (
    id_rodovia INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero SMALLINT NOT NULL,
    data_carga TIMESTAMP NOT NULL DEFAULT now(),
    UNIQUE (numero)
);

CREATE TABLE corporativo.localizacoes (
    id_localizacao INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_rodovia INT NOT NULL REFERENCES corporativo.rodovias (id_rodovia),
    km NUMERIC(6,1) NOT NULL,
    data_carga TIMESTAMP NOT NULL DEFAULT now(),
    UNIQUE (id_rodovia, km)
);

-- Consolida município + ponto na rodovia numa única entidade (mesmo papel de
-- `local_acidente` no OLTP), referenciada por `ocorrencias.id_local`.
CREATE TABLE corporativo.locais_acidente (
    id_local INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_municipio INT NOT NULL REFERENCES corporativo.municipios (id_municipio),
    id_localizacao INT NOT NULL REFERENCES corporativo.localizacoes (id_localizacao),
    data_carga TIMESTAMP NOT NULL DEFAULT now(),
    UNIQUE (id_municipio, id_localizacao)
);

-- ----------------------------
-- ASSUNTO: CLASSIFICAÇÃO DO ACIDENTE
-- ----------------------------
-- Mesmo catálogo atributo-valor do OLTP (tipo_atributo / atributo_valor_valido),
-- copiado (não recriado do zero) pelo ETL a partir do OLTP - o corporativo não
-- inventa valores válidos, só espelha o que o sistema de origem já validou.
-- tracado_via NÃO está aqui (nem no OLTP - ver db/01_schema.sql, nota
-- "DESCOBERTA"): a partir de 2017 a PRF passou a admitir mais de um traçado
-- por ocorrência, então é um atributo multivalorado próprio
-- (corporativo.tracados_via_validos/ocorrencia_tracado_via logo abaixo), não
-- parte deste catálogo genérico de valor único por tipo.

CREATE TABLE corporativo.tipos_classificacao (
    tipo_classificacao VARCHAR(30) PRIMARY KEY,
    descricao VARCHAR(60) NOT NULL,
    obrigatorio BOOLEAN NOT NULL DEFAULT TRUE,
    data_carga TIMESTAMP NOT NULL DEFAULT now()
);

-- 100: maior valor observado é um rótulo de causa_acidente com 78 caracteres
-- (anos 2017+) - mesma largura de db/01_schema.sql.atributo_valor_valido.
CREATE TABLE corporativo.classificacoes_validas (
    tipo_classificacao VARCHAR(30) NOT NULL REFERENCES corporativo.tipos_classificacao (tipo_classificacao),
    valor VARCHAR(100) NOT NULL,
    data_carga TIMESTAMP NOT NULL DEFAULT now(),
    PRIMARY KEY (tipo_classificacao, valor)
);

-- Catálogo + associativa da 9a classificação (tracado_via), espelhando
-- db/01_schema.sql.tracado_via_valido/acidente_tracado_via.
CREATE TABLE corporativo.tracados_via_validos (
    valor VARCHAR(30) PRIMARY KEY,
    data_carga TIMESTAMP NOT NULL DEFAULT now()
);

-- ----------------------------
-- ASSUNTO: VÍTIMAS
-- ----------------------------

CREATE TABLE corporativo.categorias_vitima (
    categoria VARCHAR(20) PRIMARY KEY,
    descricao VARCHAR(30) NOT NULL,
    data_carga TIMESTAMP NOT NULL DEFAULT now()
);

-- ----------------------------
-- ASSUNTO: OCORRÊNCIAS
-- ----------------------------
-- O fato operacional do corporativo: cabeçalho enxuto igual ao OLTP
-- (`acidentes`), mas com chave substituta própria (sequência corporativa,
-- independente do `id` do CSV) + par sistema_origem/id_ocorrencia_origem
-- para rastreabilidade e para admitir múltiplos anos de carga sem colisão.

CREATE SEQUENCE corporativo.seq_ocorrencias START 1;

CREATE TABLE corporativo.ocorrencias (
    id_ocorrencia BIGINT NOT NULL DEFAULT nextval('corporativo.seq_ocorrencias') PRIMARY KEY,
    sistema_origem VARCHAR(20) NOT NULL DEFAULT 'PRF-DATATRAN',
    id_ocorrencia_origem VARCHAR(50) NOT NULL,
    id_tempo INT NOT NULL REFERENCES corporativo.tempos (id_tempo),
    horario TIME NOT NULL,
    id_local INT REFERENCES corporativo.locais_acidente (id_local), -- NULL: mesmas 5 ocorrências sem uf/br/km na fonte (ver db/01_schema.sql)
    veiculos SMALLINT NOT NULL,
    data_carga TIMESTAMP NOT NULL DEFAULT now(),
    UNIQUE (sistema_origem, id_ocorrencia_origem)
);

CREATE INDEX idx_ocorrencias_tempo ON corporativo.ocorrencias (id_tempo);
CREATE INDEX idx_ocorrencias_local ON corporativo.ocorrencias (id_local);

-- Tabela associativa: mesma decomposição 4FN do OLTP (`acidente_vitima`), só
-- que ligada à chave substituta `id_ocorrencia`.
CREATE TABLE corporativo.ocorrencia_vitima (
    id_ocorrencia BIGINT NOT NULL REFERENCES corporativo.ocorrencias (id_ocorrencia),
    categoria VARCHAR(20) NOT NULL REFERENCES corporativo.categorias_vitima (categoria),
    quantidade SMALLINT NOT NULL CHECK (quantidade > 0),
    PRIMARY KEY (id_ocorrencia, categoria)
);

-- Mesmo padrão atributo-valor do OLTP (`acidente_atributo`), preservado aqui
-- de propósito: o corporativo não "desnormaliza de volta" para colunas
-- tipadas - isso só acontece no data mart em estrela (dim_classificacao_acidente),
-- que é otimizado para consulta, não para integridade por assunto.
CREATE TABLE corporativo.ocorrencia_classificacao (
    id_ocorrencia BIGINT NOT NULL REFERENCES corporativo.ocorrencias (id_ocorrencia),
    tipo_classificacao VARCHAR(30) NOT NULL,
    valor VARCHAR(100) NOT NULL,
    PRIMARY KEY (id_ocorrencia, tipo_classificacao),
    FOREIGN KEY (tipo_classificacao, valor) REFERENCES corporativo.classificacoes_validas (tipo_classificacao, valor)
);

-- Tabela associativa da 9a classificação (tracado_via), espelhando
-- db/01_schema.sql.acidente_tracado_via - 0 a N linhas por ocorrência.
CREATE TABLE corporativo.ocorrencia_tracado_via (
    id_ocorrencia BIGINT NOT NULL REFERENCES corporativo.ocorrencias (id_ocorrencia),
    valor VARCHAR(30) NOT NULL REFERENCES corporativo.tracados_via_validos (valor),
    PRIMARY KEY (id_ocorrencia, valor)
);

CREATE INDEX idx_ocorrencia_vitima_categoria ON corporativo.ocorrencia_vitima (categoria);
CREATE INDEX idx_ocorrencia_classificacao_tipo_valor ON corporativo.ocorrencia_classificacao (tipo_classificacao, valor);
CREATE INDEX idx_ocorrencia_tracado_via_valor ON corporativo.ocorrencia_tracado_via (valor);
