\c dw

-- Catálogo de metadados: documenta a origem e a regra de transformação de
-- cada campo do DW (corporativo + data_marting) - de onde vem, o que virou,
-- e por qual algoritmo de ETL. Schema genérico (mesmo desenho independente de
-- domínio); o conteúdo específico deste projeto entra via
-- metadados_seed_postgres.sql (execução manual, ver README).

CREATE SCHEMA metadados;

CREATE TABLE metadados.tipo_campo (
    id_tipo_campo INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome_tipo_campo VARCHAR(50) NOT NULL,
    descricao VARCHAR(255)
);

CREATE TABLE metadados.sistema_transacional (
    id_sistema INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome_sistema VARCHAR(100) NOT NULL,
    descricao VARCHAR(255),
    plataforma VARCHAR(100)
);

CREATE TABLE metadados.tabela_transacional (
    id_tabela INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_sistema INT NOT NULL REFERENCES metadados.sistema_transacional (id_sistema),
    nome_tabela VARCHAR(100) NOT NULL,
    descricao VARCHAR(255)
);

CREATE TABLE metadados.campo_transacional (
    id_campo INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_tabela INT NOT NULL REFERENCES metadados.tabela_transacional (id_tabela),
    id_tipo_campo INT NOT NULL REFERENCES metadados.tipo_campo (id_tipo_campo),
    nome_campo VARCHAR(100) NOT NULL,
    descricao VARCHAR(255),
    mascara_campo VARCHAR(50),
    tamanho_campo INT,
    casa_decimal INT
);

CREATE TABLE metadados.assunto_dw (
    id_assunto INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome_assunto VARCHAR(100) NOT NULL,
    descricao VARCHAR(255)
);

CREATE TABLE metadados.tabela_dw (
    id_tabela_dw INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_assunto INT NOT NULL REFERENCES metadados.assunto_dw (id_assunto),
    nome_tabela VARCHAR(100) NOT NULL,
    tipo_tabela VARCHAR(20) NOT NULL CHECK (tipo_tabela IN ('Dimensão', 'Fato', 'Corporativo')),
    grao VARCHAR(255),
    periodicidade_carga VARCHAR(50)
);

CREATE TABLE metadados.campo_dw (
    id_campo INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_tabela_dw INT NOT NULL REFERENCES metadados.tabela_dw (id_tabela_dw),
    id_tipo_campo INT NOT NULL REFERENCES metadados.tipo_campo (id_tipo_campo),
    nome_campo VARCHAR(100) NOT NULL,
    descricao VARCHAR(255),
    papel_campo VARCHAR(20) NOT NULL DEFAULT 'Atributo' CHECK (papel_campo IN ('PK', 'FK', 'Atributo')),
    tamanho_campo INT,
    casa_decimal INT
);

CREATE TABLE metadados.dado_externo (
    id_dado_externo INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome_dado_externo VARCHAR(100) NOT NULL,
    descricao VARCHAR(255),
    periodicidade VARCHAR(50)
);

CREATE TABLE metadados.dado_externo_conteudo (
    id_conteudo INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_dado_externo INT NOT NULL REFERENCES metadados.dado_externo (id_dado_externo),
    conteudo VARCHAR(255),
    data DATE,
    complemento VARCHAR(255)
);

CREATE TABLE metadados.algoritmo_etl (
    id_algoritmo INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome_algoritmo VARCHAR(150) NOT NULL,
    descricao VARCHAR(500),
    referencia_codigo VARCHAR(255)
);

-- Linhagem de um campo do DW. A origem de um campo pode ser (uma das três,
-- nunca mais de uma preenchida):
--   a) um campo transacional (id_campo_transacional) - ex.: transacional -> corporativo
--   b) OUTRO campo do DW (id_campo_dw_origem) - ex.: corporativo -> data_marting,
--      quando o ETL do mart lê do corporativo e nunca volta ao transacional
--      (ver airflow/dags/common_etl.py: dims/fato do data_marting são sempre
--      resolvidos a partir de tabelas `corporativo.*`, nunca do `datatran`)
--   c) um dado externo (id_dado_externo_conteudo) - ex.: calendário gerado,
--      constantes/regras do ETL sem nenhuma coluna de origem
-- Sem essa segunda opção (b), a única forma de documentar campos do
-- data_marting seria "pular" o corporativo e apontar direto pro transacional
-- - o que descreveria uma arquitetura diferente da que o ETL realmente
-- implementa (2 saltos: transacional -> corporativo -> data_marting).
CREATE TABLE metadados.integracao_transacional_dw (
    id_integracao INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_campo_transacional INT REFERENCES metadados.campo_transacional (id_campo),
    id_campo_dw_origem INT REFERENCES metadados.campo_dw (id_campo),
    id_campo_dw_destino INT NOT NULL REFERENCES metadados.campo_dw (id_campo),
    id_dado_externo_conteudo INT REFERENCES metadados.dado_externo_conteudo (id_conteudo),
    id_algoritmo INT REFERENCES metadados.algoritmo_etl (id_algoritmo),
    CHECK (id_campo_transacional IS NOT NULL OR id_campo_dw_origem IS NOT NULL OR id_dado_externo_conteudo IS NOT NULL)
);

CREATE INDEX idx_tabela_transacional_sistema ON metadados.tabela_transacional (id_sistema);
CREATE INDEX idx_campo_transacional_tabela ON metadados.campo_transacional (id_tabela);
CREATE INDEX idx_campo_transacional_tipo ON metadados.campo_transacional (id_tipo_campo);
CREATE INDEX idx_tabela_dw_assunto ON metadados.tabela_dw (id_assunto);
CREATE INDEX idx_campo_dw_tabela ON metadados.campo_dw (id_tabela_dw);
CREATE INDEX idx_campo_dw_tipo ON metadados.campo_dw (id_tipo_campo);
CREATE INDEX idx_dado_externo_conteudo_dado ON metadados.dado_externo_conteudo (id_dado_externo);
CREATE INDEX idx_integracao_campo_transacional ON metadados.integracao_transacional_dw (id_campo_transacional);
CREATE INDEX idx_integracao_campo_dw_origem ON metadados.integracao_transacional_dw (id_campo_dw_origem);
CREATE INDEX idx_integracao_campo_dw_destino ON metadados.integracao_transacional_dw (id_campo_dw_destino);
CREATE INDEX idx_integracao_dado_externo_conteudo ON metadados.integracao_transacional_dw (id_dado_externo_conteudo);
CREATE INDEX idx_integracao_algoritmo ON metadados.integracao_transacional_dw (id_algoritmo);
