CREATE DATABASE dw;

\c dw

CREATE SCHEMA corporativo;

-- ============================================================================
-- Data Warehouse corporativo (camada "corporativo"), modelado à Inmon:
-- orientado por assunto, integrado, não-volátil e variante no tempo. Fonte:
-- banco `datatran` (OLTP, ver ../db/01_schema.sql) — acidentes de trânsito em
-- rodovias federais registrados pela PRF.
--
-- As 4 propriedades de Inmon aplicadas aqui:
--
--   ORIENTADO POR ASSUNTO: as tabelas não replicam a aplicação de origem
--   (que já é assunto único, "acidentes"), mas são organizadas pelos temas de
--   negócio que um analista corporativo consulta - Tempo, Geografia e Via,
--   Classificação do Acidente, Vítimas, Ocorrências -
--   independente de qualquer detalhe de implementação do OLTP (ex.: o OLTP
--   guarda "onde" via `local_acidente`, aqui isso é o assunto "Geografia e
--   Via" por completo, `municipios`+`rodovias`+`localizacoes`+`locais_acidente`).
--
--   INTEGRADO: toda tabela de fato (`ocorrencias`) carrega `sistema_origem`
--   (fixo em 'PRF-DATATRAN' hoje) + `id_ocorrencia_origem` (chave natural do
--   CSV de origem) ao lado da chave substituta corporativa. Isso é o que dá
--   ao DW a propriedade de "integrado" do Inmon mesmo quando, como aqui,
--   existe hoje uma única fonte real: o objetivo é poder empilhar
--   `datatran2008.csv`, `datatran2009.csv` etc. no mesmo
--   `corporativo.ocorrencias` ano após ano, sem colisão de PK (o `id` do CSV
--   é único só dentro de um ano) e sem reprocessar o histórico já carregado
--   - exatamente o cenário de "integrar múltiplas cargas da mesma família de
--   sistemas" que a propriedade motiva, ainda que aqui não haja um segundo
--   sistema *diferente* como no projeto de referência (Mercearia+Northwind).
--
--   NÃO-VOLÁTIL: `ocorrencias`/`ocorrencia_vitima` são append-only - uma vez
--   carregada, uma ocorrência nunca sofre UPDATE, só INSERT de ocorrências
--   novas (ver airflow/dags/carga_incremental_dw.py).
--
--   VARIANTE NO TEMPO: cada ocorrência é permanentemente amarrada à
--   `id_tempo` em que aconteceu; a série histórica cresce, nunca é
--   sobrescrita.
--
-- Diferença deliberada em relação ao projeto de referência (DW_pos_atividades):
-- lá, `clientes`/`funcionarios`/`produtos` precisam de histórico versionado
-- (upsert_historizado, SCD2) porque atributos descritivos (renda, cargo,
-- preço) mudam ao longo do tempo para a MESMA chave natural. Aqui, nenhuma
-- entidade de apoio (`ufs`, `municipios`, `rodovias`, `localizacoes`, os 8
-- catálogos de classificação, `categorias_vitima`) tem atributo descritivo
-- que mude no dataset de origem - nome de município e sigla de UF são
-- efetivamente estáticos. Por isso este schema não usa upsert_historizado em
-- lugar nenhum: todas as tabelas de apoio usam upsert simples (existe ou não
-- pela chave natural), e a única coisa genuinamente variante no tempo é a
-- CHEGADA de ocorrências novas, não a mudança de atributos de uma dimensão
-- de apoio.
--
-- REMODELAGEM (pós ajuste do transacional): a 1a versão deste schema mantinha
-- a classificação do acidente como atributo-valor genérico no corporativo
-- (`tipos_classificacao`/`classificacoes_validas`/`ocorrencia_classificacao`),
-- espelhando o EAV que o OLTP tinha então. O OLTP (db/01_schema.sql) trocou
-- esse EAV por 8 colunas tipadas + 8 catálogos dedicados, pelo motivo
-- documentado lá (antipadrão quando o conjunto de atributos é fixo e
-- conhecido de antemão - Karwin, "SQL Antipatterns", cap. 6). Esse motivo não
-- é específico do OLTP: continuar EAV aqui depois que a fonte deixou de ser
-- EAV reintroduziria, na camada corporativa, a mesma perda de tipagem/NOT
-- NULL por atributo - sem nenhum ganho de integração em troca (o conjunto de
-- 8 classificações é o mesmo em qualquer ano de carga). Por isso o
-- corporativo foi remodelado para a mesma decomposição do OLTP: 8 colunas
-- próprias em `ocorrencias`, cada uma FK pra seu catálogo dedicado (ver
-- ASSUNTO: CLASSIFICAÇÃO DO ACIDENTE abaixo).
-- ============================================================================

-- ----------------------------
-- ASSUNTO: TEMPO
-- ----------------------------
-- Calendário corporativo, gerado uma vez (não vem do sistema transacional).
-- Cobre 2000-2035 para admitir cargas de anos de datatran anteriores e
-- futuros ao 2007 hoje disponível em dataset/datatran2007.csv.

CREATE TABLE corporativo.tempos (
    id_tempo INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data DATE NOT NULL,
    dia INT NOT NULL,
    mes INT NOT NULL,
    nome_mes VARCHAR(20) NOT NULL,
    trimestre INT NOT NULL,
    ano INT NOT NULL,
    dia_semana VARCHAR(20) NOT NULL,
    flag_fim_semana BOOLEAN NOT NULL,
    UNIQUE (data)
);

INSERT INTO corporativo.tempos (data, dia, mes, nome_mes, trimestre, ano, dia_semana, flag_fim_semana)
SELECT
    d::date,
    EXTRACT(DAY FROM d)::int,
    EXTRACT(MONTH FROM d)::int,
    TO_CHAR(d, 'TMMonth'),
    EXTRACT(QUARTER FROM d)::int,
    EXTRACT(YEAR FROM d)::int,
    TO_CHAR(d, 'TMDay'),
    EXTRACT(ISODOW FROM d) IN (6, 7)
FROM generate_series('2000-01-01'::date, '2035-12-31'::date, interval '1 day') AS d;

-- ----------------------------
-- ASSUNTO: GEOGRAFIA E VIA
-- ----------------------------
-- Mesma decomposição do OLTP (uf / municipio / rodovia / localizacao /
-- local_acidente), agora com chave substituta própria do corporativo e
-- `data_carga` de auditoria - populadas por upsert simples a partir do OLTP
-- (ver common_etl.get_or_create_uf / get_or_create_municipio / etc.).

CREATE TABLE corporativo.ufs (
    id_uf INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sigla CHAR(2) NOT NULL,
    nome VARCHAR(30) NOT NULL,
    data_carga TIMESTAMP NOT NULL DEFAULT now(),
    UNIQUE (sigla)
);

CREATE TABLE corporativo.municipios (
    id_municipio INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(60) NOT NULL,
    id_uf INT NOT NULL REFERENCES corporativo.ufs (id_uf),
    data_carga TIMESTAMP NOT NULL DEFAULT now(),
    UNIQUE (nome, id_uf)
);

CREATE TABLE corporativo.rodovias (
    id_rodovia INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero SMALLINT NOT NULL,
    data_carga TIMESTAMP NOT NULL DEFAULT now(),
    UNIQUE (numero)
);

CREATE TABLE corporativo.localizacoes (
    id_localizacao INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_rodovia INT NOT NULL REFERENCES corporativo.rodovias (id_rodovia),
    km NUMERIC(6,1) NOT NULL,
    data_carga TIMESTAMP NOT NULL DEFAULT now(),
    UNIQUE (id_rodovia, km)
);

-- Consolida município + ponto na rodovia numa única entidade (mesmo papel de
-- `local_acidente` no OLTP), referenciada por `ocorrencias.id_local`.
CREATE TABLE corporativo.locais_acidente (
    id_local INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_municipio INT NOT NULL REFERENCES corporativo.municipios (id_municipio),
    id_localizacao INT NOT NULL REFERENCES corporativo.localizacoes (id_localizacao),
    data_carga TIMESTAMP NOT NULL DEFAULT now(),
    UNIQUE (id_municipio, id_localizacao)
);

-- ----------------------------
-- ASSUNTO: CLASSIFICAÇÃO DO ACIDENTE
-- ----------------------------
-- 8 catálogos dedicados, um por classificação de valor único - mesma
-- decomposição do OLTP atual (db/01_schema.sql: causa_acidente_valido,
-- tipo_acidente_valido, ..., uso_solo_valido), copiados (não recriados do
-- zero) pelo ETL a partir do OLTP - o corporativo não inventa valores
-- válidos, só espelha o que o sistema de origem já validou. Substituem o
-- catálogo atributo-valor genérico (tipo_atributo/atributo_valor_valido) que
-- uma versão anterior deste schema tinha - ver nota "REMODELAGEM" no
-- cabeçalho deste arquivo.
--
-- tracado_via NÃO está aqui (nem no OLTP - ver db/01_schema.sql, nota
-- "DESCOBERTA"): a partir de 2017 a PRF passou a admitir mais de um traçado
-- por ocorrência, então é um atributo multivalorado próprio
-- (corporativo.tracados_via_validos/ocorrencia_tracado_via logo abaixo), não
-- um catálogo de valor único por tipo.

CREATE TABLE corporativo.causas_acidente (
    valor VARCHAR(100) PRIMARY KEY,  -- maior observado: 78 (rótulos 2017+)
    data_carga TIMESTAMP NOT NULL DEFAULT now()
);

CREATE TABLE corporativo.tipos_acidente (
    valor VARCHAR(60) PRIMARY KEY,  -- maior observado: 42
    data_carga TIMESTAMP NOT NULL DEFAULT now()
);

CREATE TABLE corporativo.classificacoes_acidente (
    valor VARCHAR(30) PRIMARY KEY,  -- maior observado: 19
    data_carga TIMESTAMP NOT NULL DEFAULT now()
);

CREATE TABLE corporativo.fases_dia (
    valor VARCHAR(20) PRIMARY KEY,  -- maior observado: 11
    data_carga TIMESTAMP NOT NULL DEFAULT now()
);

CREATE TABLE corporativo.sentidos_via (
    valor VARCHAR(20) PRIMARY KEY,  -- maior observado: 13
    data_carga TIMESTAMP NOT NULL DEFAULT now()
);

CREATE TABLE corporativo.condicoes_metereologicas (
    valor VARCHAR(30) PRIMARY KEY,  -- maior observado: 16
    data_carga TIMESTAMP NOT NULL DEFAULT now()
);

CREATE TABLE corporativo.tipos_pista (
    valor VARCHAR(20) PRIMARY KEY,  -- maior observado: 8
    data_carga TIMESTAMP NOT NULL DEFAULT now()
);

CREATE TABLE corporativo.usos_solo (
    valor VARCHAR(20) PRIMARY KEY,  -- maior observado: 6
    data_carga TIMESTAMP NOT NULL DEFAULT now()
);

-- Catálogo + associativa da 9a classificação (tracado_via), espelhando
-- db/01_schema.sql.tracado_via_valido/acidente_tracado_via.
CREATE TABLE corporativo.tracados_via_validos (
    valor VARCHAR(30) PRIMARY KEY,
    data_carga TIMESTAMP NOT NULL DEFAULT now()
);

-- ----------------------------
-- ASSUNTO: VÍTIMAS
-- ----------------------------

CREATE TABLE corporativo.categorias_vitima (
    categoria VARCHAR(20) PRIMARY KEY,
    descricao VARCHAR(30) NOT NULL,
    data_carga TIMESTAMP NOT NULL DEFAULT now()
);

-- ----------------------------
-- ASSUNTO: OCORRÊNCIAS
-- ----------------------------
-- O fato operacional do corporativo: cabeçalho enxuto igual ao OLTP
-- (`acidentes`), mas com chave substituta própria (sequência corporativa,
-- independente do `id` do CSV) + par sistema_origem/id_ocorrencia_origem
-- para rastreabilidade e para admitir múltiplos anos de carga sem colisão.
-- As 8 classificações de valor único entram como colunas próprias, cada uma
-- FK pra um catálogo dedicado (ver ASSUNTO: CLASSIFICAÇÃO DO ACIDENTE acima)
-- - mesma decomposição do OLTP (db/01_schema.sql.acidentes), não mais um EAV
-- (ver nota "REMODELAGEM" no cabeçalho deste arquivo). `NOT NULL` só em
-- `sentido_via`, pelo mesmo levantamento empírico do OLTP (0 nulos nas
-- 2.237.189 ocorrências verificadas; as outras 7 têm nulos reais).

CREATE SEQUENCE corporativo.seq_ocorrencias START 1;

CREATE TABLE corporativo.ocorrencias (
    id_ocorrencia BIGINT NOT NULL DEFAULT nextval('corporativo.seq_ocorrencias') PRIMARY KEY,
    sistema_origem VARCHAR(20) NOT NULL DEFAULT 'PRF-DATATRAN',
    id_ocorrencia_origem VARCHAR(50) NOT NULL,
    id_tempo INT NOT NULL REFERENCES corporativo.tempos (id_tempo),
    horario TIME NOT NULL,
    id_local INT REFERENCES corporativo.locais_acidente (id_local), -- NULL: mesmas 5 ocorrências sem uf/br/km na fonte (ver db/01_schema.sql)
    veiculos SMALLINT NOT NULL,

    causa_acidente          VARCHAR(100) REFERENCES corporativo.causas_acidente (valor),
    tipo_acidente           VARCHAR(60) REFERENCES corporativo.tipos_acidente (valor),
    classificacao_acidente  VARCHAR(30) REFERENCES corporativo.classificacoes_acidente (valor),
    fase_dia                VARCHAR(20) REFERENCES corporativo.fases_dia (valor),
    sentido_via             VARCHAR(20) NOT NULL REFERENCES corporativo.sentidos_via (valor),
    condicao_metereologica  VARCHAR(30) REFERENCES corporativo.condicoes_metereologicas (valor),
    tipo_pista               VARCHAR(20) REFERENCES corporativo.tipos_pista (valor),
    uso_solo                VARCHAR(20) REFERENCES corporativo.usos_solo (valor),

    data_carga TIMESTAMP NOT NULL DEFAULT now(),
    UNIQUE (sistema_origem, id_ocorrencia_origem)
);

CREATE INDEX idx_ocorrencias_tempo ON corporativo.ocorrencias (id_tempo);
CREATE INDEX idx_ocorrencias_local ON corporativo.ocorrencias (id_local);
CREATE INDEX idx_ocorrencias_causa ON corporativo.ocorrencias (causa_acidente);
CREATE INDEX idx_ocorrencias_tipo ON corporativo.ocorrencias (tipo_acidente);
CREATE INDEX idx_ocorrencias_classificacao ON corporativo.ocorrencias (classificacao_acidente);
CREATE INDEX idx_ocorrencias_fase_dia ON corporativo.ocorrencias (fase_dia);
CREATE INDEX idx_ocorrencias_sentido_via ON corporativo.ocorrencias (sentido_via);
CREATE INDEX idx_ocorrencias_condicao_metereologica ON corporativo.ocorrencias (condicao_metereologica);
CREATE INDEX idx_ocorrencias_tipo_pista ON corporativo.ocorrencias (tipo_pista);
CREATE INDEX idx_ocorrencias_uso_solo ON corporativo.ocorrencias (uso_solo);

-- Tabela associativa: mesma decomposição 4FN do OLTP (`acidente_vitima`), só
-- que ligada à chave substituta `id_ocorrencia`.
CREATE TABLE corporativo.ocorrencia_vitima (
    id_ocorrencia BIGINT NOT NULL REFERENCES corporativo.ocorrencias (id_ocorrencia),
    categoria VARCHAR(20) NOT NULL REFERENCES corporativo.categorias_vitima (categoria),
    quantidade SMALLINT NOT NULL CHECK (quantidade > 0),
    PRIMARY KEY (id_ocorrencia, categoria)
);

-- Tabela associativa da 9a classificação (tracado_via), espelhando
-- db/01_schema.sql.acidente_tracado_via - 0 a N linhas por ocorrência.
CREATE TABLE corporativo.ocorrencia_tracado_via (
    id_ocorrencia BIGINT NOT NULL REFERENCES corporativo.ocorrencias (id_ocorrencia),
    valor VARCHAR(30) NOT NULL REFERENCES corporativo.tracados_via_validos (valor),
    PRIMARY KEY (id_ocorrencia, valor)
);

CREATE INDEX idx_ocorrencia_vitima_categoria ON corporativo.ocorrencia_vitima (categoria);
CREATE INDEX idx_ocorrencia_tracado_via_valor ON corporativo.ocorrencia_tracado_via (valor);
